workflows:
  ios-workflow:
    name: iOS Build
    environment:
      node: latest
      xcode: latest
    scripts:
      - name: Debug directory
        script: |
          pwd
          ls -la
          ls App.js || echo "App.js not found"
          ls ios/Podfile || echo "Podfile not found"
          ls ios/SimpleAppRN.xcworkspace || echo "Workspace not found"
      - name: Install dependencies
        script: |
          npm install
      - name: Pod install
        script: |
          cd ios || { echo "ios directory not found"; exit 1; }
          pod cache clean --all
          pod install --repo-update || { echo "Pod install failed"; exit 1; }
          cd ..
      - name: Build unsigned IPA
        script: |
          cd ios
          xcodebuild -workspace SimpleAppRN.xcworkspace \
            -scheme SimpleAppRN \
            -configuration Release \
            -archivePath "../build/SimpleAppRN.xcarchive" \
            -allowProvisioningUpdates \
            -destination generic/platform=iOS \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            archive || { echo "Archive failed"; exit 1; }
          xcodebuild -exportArchive \
            -archivePath "../build/SimpleAppRN.xcarchive" \
            -exportPath "../build" \
            -exportOptionsPlist "../exportOptions.plist" || { echo "Export IPA failed"; exit 1; }
          cd ..
      - name: Create exportOptions.plist
        script: |
          cat > ios/exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>development</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>compileBitcode</key>
            <false/>
            <key>uploadBitcode</key>
            <false/>
            <key>uploadSymbols</key>
            <false/>
          </dict>
          </plist>
          EOF
    artifacts:
      - ios/build/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com  # Your email
