workflows:
  ios-workflow:
    name: iOS Build
    environment:
      node: latest
      xcode: latest
    scripts:
      - name: Debug directory
        script: |
          pwd
          ls -la
          ls App.js || echo "App.js not found"
          ls ios/Podfile || echo "Podfile not found"
          ls ios/SimpleAppRN.xcworkspace || echo "Workspace not found"
      - name: Install dependencies
        script: |
          npm install
      - name: Pod_.
