require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'SimpleAppRN' do
  config = use_native_modules!
  use_react_native!(
    :path => '../node_modules/react-native',
    :hermes_enabled => false
  )

  use_flipper!() if !ENV['CI']
  post_install do |installer|
    react_native_post_install(installer)
  end
end
